### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by image357** [brunoborges/toml-schema#9]
I'm planing to use toml for my projects and stumbled across your toml schema validator.
However, it seems that you haven't released it under any licence.
Do you plan to publish it for open source?

**Comment by eksortso** [comment]
Since it's published in the open on GitHub, presumably it'll be licensed as open source.

However, this isn't a validator. It's a proposed standard for defining schemas for [TOML](https://toml.io) documents.

You can go to the TOML standard project and check the [TOML implementations for your language](https://github.com/toml-lang/toml/wiki) there.

**Comment by image357** [comment]
Thanks for answering. In fact, if you don't put any license on your project, it means that all rights are reserved, i.e. it won't be open source. See also a related post at stackexchange:

https://opensource.stackexchange.com/a/1721

If you don't want to publish it under an open source license, would you allow use and redistribution for testing purposes?

**Comment by brunoborges** [comment]
@image357 not sure how you will distribute and test a work in progress proposal. If the lack of a license in this repo is holding you back from contributing, I will happily add a license though.

**Comment by image357** [comment]
Well ok. It seems I missunderstood your repo. Thought that it was some implementation of a TOML schema validator. Nevermind then. The point about the licence still holds, though. Noone can actually do anymore than viewing your files if you don't put any licence.

**Comment by eksortso** [comment]
@image357 That is true about the licensing. Thank you.

@brunoborges It would probably benefit TOML Schema, going forward, to add the same license that the TOML standard has. We can discuss that elsewhere.

**Comment by brunoborges** [comment]
Just did! :-)
